export const GET_WORKOUT = 'GET_WORKOUT'
export const GET_WORKOUTS = 'GET_WORKOUTS'
export const FITNESS_ERROR = 'FITNESS_ERROR'
export const FILTER_FITNESS = 'FILTER_FITNESS'
export const SORT_FITNESS = 'SORT_FITNESS'

export const GET_POST = 'GET_POST'
export const GET_POSTS = 'GET_POSTS'
export const POST_ERROR = 'POST_ERROR'
export const FILTER_POSTS = 'FILTER_POSTS'
export const SORT_POSTS = 'SORT_POSTS'

export const GET_CONFIG = 'GET_CONFIG'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const ADD_ANALYTIC = 'ADD_ANALYTIC'
export const GET_ANALYTICS = 'GET_ANALYTICS'
export const ANALYTICS_ERROR = 'ANALYTICS_ERROR'
