export const ADD_WORKOUT = 'ADD_WORKOUT'
export const UPDATE_WORKOUT = 'UPDATE_WORKOUT'
export const REMOVE_WORKOUT = 'REMOVE_WORKOUT'
export const GET_WORKOUT = 'GET_WORKOUT'
export const GET_WORKOUTS = 'GET_WORKOUTS'
export const LOAD_FITNESS = 'LOAD_FITNESS'
export const FITNESS_ERROR = 'FITNESS_ERROR'

export const ADD_POST = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const REMOVE_POST = 'REMOVE_POST'
export const GET_POST = 'GET_POST'
export const GET_POSTS = 'GET_POSTS'
export const LOAD_POSTS = 'LOAD_POSTS'
export const POST_ERROR = 'POST_ERROR'

export const ADD_SETTINGS = 'ADD_SETTINGS'
export const GET_SETTINGS = 'GET_SETTINGS'
export const SETTINGS_ERROR = 'SETTINGS_ERROR'
